name: Build & Upload Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'
    # Install the gems in the gemfile & install ncftp
    - name: Setup Environment.
      run: |
        bundle install
        sudo apt-get install -y ncftp

    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.ftp_host }}
        ftp_username: ${{ secrets.ftp_user }}
        ftp_password: ${{ secrets.ftp_password }}
        local_source_dir: "_site"
        dist_target_dir: "public_html"
        delete: "true"
        only_newer: "true"
